### ISSUE TITLE
Forgot to pre-populate config file

### ISSUE THREAD

**Issue by NaythanTouqe** [ShockBock/TheOpenWastes#10]
look like you forgot to pre-populate "mouse" section of your initial first time.
(config file not yet been created or already created but don't have "mouse" section added yet) config dict. 
I'm not surprise you didn't catch this one. 
it sit on your computer but it not going with the repo tho.
this should be easy fix.

![Screenshot 2024-08-31 153228](https://github.com/user-attachments/assets/af4f881f-cdea-40c9-b33f-29aab4439e1a)

**Comment by NaythanTouqe** [comment]
### Solution:
add this to `res://scripts/singletons/config_file_handler.gd` after line 24
```
		config.set_value("mouse", "mouse_sensitivity", 0.03)
		config.set_value("mouse", "invert_mouse", false)
```

**Comment by NaythanTouqe** [comment]
btw. you have to do it for all branch. I check it. **OR** just merge  it all in to "DEV" branch. 
I recommend you to rebase it. it keep history clear. because you might want to delete the branch you don't use.
But if you don't care. then, if shit work, it work. We're not gonna be picky. Aren't we?

**Comment by NaythanTouqe** [comment]
I'm ESL btw. apologize for my typo.

**Comment by ShockBock** [comment]
Thanks for that. I've added the code to the branch [12_expanded_procgen_building](https://github.com/ShockBock/TheOpenWastes/tree/12_expanded_procgen_building). I tried adding it to main, but I had problems doing so. I think the best thing to do is wait until I pull 12_expanded_procgen_building to main and to treat 12_expanded_procgen_building as the main branch to work from at the moment.
